### ISSUE TITLE
Cannot run build.sh to setup xenserver build env

### ISSUE THREAD

**Issue by kongxx** [xenserver/xenserver-build-env#33]
Hi, 

I am trying to build a xenserver build env, but after I added "DOCKER_OPTS="--dns 10.80.16.125 --dns 10.80.16.126 -s devicemapper" in /etc/default/docker file and restarted docker service, when I run build script,  I got the following error message
# 
# sudo ./build.sh

Sending build context to Docker daemon 24.06 kB
Sending build context to Docker daemon
Step 0 : FROM xenserver/xenserver-base
Pulling repository xenserver/xenserver-base
341996e79147: Download complete
Status: Downloaded newer image for xenserver/xenserver-base:latest
 ---> 341996e79147
Step 1 : MAINTAINER John Else john.else@citrix.com
 ---> Running in b61312e4dad7
 ---> 84ceb7156562
Removing intermediate container b61312e4dad7
Step 2 : COPY files/yum.conf /etc/yum.conf
 ---> 6c638d82fbab
Removing intermediate container 85001f1af008
Step 3 : RUN mkdir -p /etc/yum.repos.d.xs
 ---> Running in c6dd7db30020
 ---> d3693d5e1076
Removing intermediate container c6dd7db30020
Step 4 : COPY files/Citrix.repo.in /tmp/Citrix.repo.in
 ---> 3bd36c5ae68b
Removing intermediate container 4158ae7e08e0
Step 5 : COPY files/RPM-GPG-KEY-Citrix-6.6 /etc/pki/rpm-gpg/RPM-GPG-KEY-Citrix-6.6
 ---> 2a4943d8dbf4
Removing intermediate container 4954b2344a4d
Step 6 : RUN yum install -y             git             make             mercurial             mock             rpm-build             rpm-python             sudo             yum-utils
 ---> Running in 49750d8c5407
Loaded plugins: fastestmirror
Loaded plugins: fastestmirror
http://www.uk.xensource.com/linux/distros/CentOS/7.0.1406/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://www.uk.xensource.com/linux/distros/CentOS/7.0.1406/os/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 30386 milliseconds')
Trying other mirror.
http://www.uk.xensource.com/linux/distros/CentOS/7.0.1406/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://www.uk.xensource.com/linux/distros/CentOS/7.0.1406/os/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 30387 milliseconds')
Trying other mirror.
...
 One of the configured repositories failed (base),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

```
 1. Contact the upstream for the repository and get them to fix the problem.

 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    upstream. This is most often useful if you are using a newer
    distribution release than is supported by the repository (and the
    packages for the previous distribution release still work).

 3. Disable the repository, so yum won't use it by default. Yum will then
    just ignore the repository until you permanently enable it again or use
    --enablerepo for temporary usage:

        yum-config-manager --disable base

 4. Configure the failing repository to be skipped, if it is unavailable.
    Note that yum will try to contact the repo. when it runs most commands,
    so will have to try and fail each time (and thus. yum will be be much
    slower). If it is a very temporary problem though, this is often a nice
    compromise:

        yum-config-manager --save --setopt=base.skip_if_unavailable=true
```

...
# 

Could you help to check what is problem?

**Comment by johnelse** [comment]
Hi, and thanks for the bug report.

At the moment this environment uses a private yum repo to download build dependencies.

If you want to try to get it working, I recommend using [buildroot](https://github.com/xenserver/buildroot) to build the dependencies and then host the built RPMs in your own yum repo.

Hope this helps!

**Comment by johnelse** [comment]
xenserver-build-env now works against a public yum repo - please take a look at the updated instructions in https://github.com/xenserver/xenserver-build-env/blob/master/README.md
